package com.polaris.blog.pojo;

import java.util.Date;

public class Article {
    private BlogUser blogUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.title
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.user_id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.category_id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.content
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.type
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.state
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.summary
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.labels
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String labels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.cover
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.view_count
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.create_time
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.update_time
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    private Date updateTime;

    public BlogUser getBlogUser() {
        return blogUser;
    }

    public void setBlogUser(BlogUser blogUser) {
        this.blogUser = blogUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.id
     *
     * @return the value of tb_article.id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.id
     *
     * @param id the value for tb_article.id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.title
     *
     * @return the value of tb_article.title
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.title
     *
     * @param title the value for tb_article.title
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.user_id
     *
     * @return the value of tb_article.user_id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.user_id
     *
     * @param userId the value for tb_article.user_id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.category_id
     *
     * @return the value of tb_article.category_id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.category_id
     *
     * @param categoryId the value for tb_article.category_id
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.content
     *
     * @return the value of tb_article.content
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.content
     *
     * @param content the value for tb_article.content
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.type
     *
     * @return the value of tb_article.type
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.type
     *
     * @param type the value for tb_article.type
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.state
     *
     * @return the value of tb_article.state
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.state
     *
     * @param state the value for tb_article.state
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.summary
     *
     * @return the value of tb_article.summary
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.summary
     *
     * @param summary the value for tb_article.summary
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.labels
     *
     * @return the value of tb_article.labels
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getLabels() {
        return labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.labels
     *
     * @param labels the value for tb_article.labels
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setLabels(String labels) {
        this.labels = labels == null ? null : labels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.cover
     *
     * @return the value of tb_article.cover
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.cover
     *
     * @param cover the value for tb_article.cover
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.view_count
     *
     * @return the value of tb_article.view_count
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.view_count
     *
     * @param viewCount the value for tb_article.view_count
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.create_time
     *
     * @return the value of tb_article.create_time
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.create_time
     *
     * @param createTime the value for tb_article.create_time
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.update_time
     *
     * @return the value of tb_article.update_time
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.update_time
     *
     * @param updateTime the value for tb_article.update_time
     *
     * @mbg.generated Sun Oct 18 15:54:40 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}