package com.polaris.blog.pojo;

import com.polaris.blog.utils.Constants;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.parent_content
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String parentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.article_id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.user_id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.user_avatar
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String userAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.user_name
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.state
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String state = Constants.Comment.STATE_PUBLISH;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.create_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.update_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_comment.comment_content
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.id
     *
     * @return the value of tb_comment.id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.id
     *
     * @param id the value for tb_comment.id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.parent_content
     *
     * @return the value of tb_comment.parent_content
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getParentContent() {
        return parentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.parent_content
     *
     * @param parentContent the value for tb_comment.parent_content
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setParentContent(String parentContent) {
        this.parentContent = parentContent == null ? null : parentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.article_id
     *
     * @return the value of tb_comment.article_id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.article_id
     *
     * @param articleId the value for tb_comment.article_id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.user_id
     *
     * @return the value of tb_comment.user_id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.user_id
     *
     * @param userId the value for tb_comment.user_id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.user_avatar
     *
     * @return the value of tb_comment.user_avatar
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.user_avatar
     *
     * @param userAvatar the value for tb_comment.user_avatar
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar == null ? null : userAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.user_name
     *
     * @return the value of tb_comment.user_name
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.user_name
     *
     * @param userName the value for tb_comment.user_name
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.state
     *
     * @return the value of tb_comment.state
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.state
     *
     * @param state the value for tb_comment.state
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.create_time
     *
     * @return the value of tb_comment.create_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.create_time
     *
     * @param createTime the value for tb_comment.create_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.update_time
     *
     * @return the value of tb_comment.update_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.update_time
     *
     * @param updateTime the value for tb_comment.update_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.comment_content
     *
     * @return the value of tb_comment.comment_content
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.comment_content
     *
     * @param commentContent the value for tb_comment.comment_content
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}