package com.polaris.blog.pojo;

import java.util.Date;

public class FriendLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.name
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.logo
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.url
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.order
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private Integer order = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.state
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private String state = "1";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.create_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend_link.update_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.id
     *
     * @return the value of tb_friend_link.id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.id
     *
     * @param id the value for tb_friend_link.id
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.name
     *
     * @return the value of tb_friend_link.name
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.name
     *
     * @param name the value for tb_friend_link.name
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.logo
     *
     * @return the value of tb_friend_link.logo
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.logo
     *
     * @param logo the value for tb_friend_link.logo
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.url
     *
     * @return the value of tb_friend_link.url
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.url
     *
     * @param url the value for tb_friend_link.url
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.order
     *
     * @return the value of tb_friend_link.order
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.order
     *
     * @param order the value for tb_friend_link.order
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.state
     *
     * @return the value of tb_friend_link.state
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.state
     *
     * @param state the value for tb_friend_link.state
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.create_time
     *
     * @return the value of tb_friend_link.create_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.create_time
     *
     * @param createTime the value for tb_friend_link.create_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend_link.update_time
     *
     * @return the value of tb_friend_link.update_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend_link.update_time
     *
     * @param updateTime the value for tb_friend_link.update_time
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}