package com.polaris.blog.pojo;

import java.util.Date;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.id
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.user_id
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.url
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.path
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.content_type
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.original_name
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String originalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.state
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.state
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.create_time
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.update_time
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.id
     *
     * @return the value of tb_image.id
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.id
     *
     * @param id the value for tb_image.id
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.user_id
     *
     * @return the value of tb_image.user_id
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.user_id
     *
     * @param userId the value for tb_image.user_id
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.url
     *
     * @return the value of tb_image.url
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.url
     *
     * @param url the value for tb_image.url
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.path
     *
     * @return the value of tb_image.path
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.path
     *
     * @param path the value for tb_image.path
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.content_type
     *
     * @return the value of tb_image.content_type
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.content_type
     *
     * @param contentType the value for tb_image.content_type
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.original_name
     *
     * @return the value of tb_image.original_name
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public String getOriginalName() {
        return originalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.original_name
     *
     * @param originalName the value for tb_image.original_name
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setOriginalName(String originalName) {
        this.originalName = originalName == null ? null : originalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.state
     *
     * @return the value of tb_image.state
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.state
     *
     * @param state the value for tb_image.state
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * @return
     */
    public String getCategory() {
        return category;
    }

    /**
     * @param category
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.create_time
     *
     * @return the value of tb_image.create_time
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.create_time
     *
     * @param createTime the value for tb_image.create_time
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.update_time
     *
     * @return the value of tb_image.update_time
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.update_time
     *
     * @param updateTime the value for tb_image.update_time
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}