# 自定义配置，通过@value读取
polaris.blog.image.save-path: D:\images
polaris.blog.image.max-size: 2097152 #1024*1024*2
# 控制Swagger的开关
polaris.blog.swagger.enable: true
server:
  port: 8085
spring:
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    username: root
    password: 1234321
    url: jdbc:mysql://mpolaris.top:3306/mpolaris_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMills: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: mpolaris.top
    port: 6379
    password: 1234321
  data:
    solr:
      host: http://mpolaris.top:8983/solr/mpolaris_blog_system_core
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  # 配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  auto-dialect: mysql
  # 配置分页参数合理化功能，默认是false
  # 启用合理化时，如果 pageNum<1 会查询第一页，如果 pageNum>totalPage会查询最后一页
  # 禁用合理化时，如果pageNum<1或pageNum>totalPage会返回空数据
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，
  # 自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据
  # 属性名取值; 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射
  # 的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;
  # reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql
