package com.polaris.blog.dao;

import com.polaris.blog.pojo.BlogUser;
import java.util.List;

public interface BlogUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int insert(BlogUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    BlogUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    List<BlogUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int updateByPrimaryKey(BlogUser record);

    /**
     * 通过用户名查用户信息
     * @param username
     * @return
     */
    BlogUser selectByUsername(String username);

    /**
     * 通过邮箱查用户信息
     * @param email
     * @return
     */
    BlogUser selectByEmail(String email);

    /**
     * 通过修改用户的状态来删除用户
     * @param userId
     * @return
     */
    int updateUserStateForDelete(String userId);

    /**
     * 根据邮箱修改密码
     * @param password
     * @param email
     * @return
     */
    int updatePasswordByEmail(String password,String email);

    /**
     * 根据id修改邮箱
     * @param email
     * @param id
     * @return
     */
    int updateEmailById(String email,String id);
}