package com.polaris.blog.dao;

import com.polaris.blog.pojo.Category;
import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    Category selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int updateByPrimaryKey(Category record);

    int updateStatusById(String id);

    List<Category> selectAllByStatus();
}