package com.polaris.blog.dao;

import com.polaris.blog.pojo.DailyViewCount;
import java.util.List;

public interface DailyViewCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_view_count
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_view_count
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int insert(DailyViewCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_view_count
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    DailyViewCount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_view_count
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    List<DailyViewCount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_daily_view_count
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int updateByPrimaryKey(DailyViewCount record);
}