package com.polaris.blog.dao;

import com.polaris.blog.pojo.Image;
import java.util.List;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    Image selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    List<Image> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_image
     *
     * @mbg.generated Wed Oct 14 14:54:46 CST 2020
     */
    int updateByPrimaryKey(Image record);

    /**
     * 查询所有state为1的
     * @return
     */
    List<Image> selectAllByState();

    /**
     * 通过修改用户状态来删除用户
     * @param imageId
     * @return
     */
    int updateStateByImageId(String imageId);
}