package com.polaris.blog.dao;

import com.polaris.blog.pojo.Label;
import java.util.List;

public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    Label selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    List<Label> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int updateByPrimaryKey(Label record);

    int updateCountByName(String label);
}