package com.polaris.blog.dao;

import com.polaris.blog.pojo.RefreshToken;
import java.util.List;

public interface RefreshTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_refresh_token
     *
     * @mbg.generated Mon Oct 12 11:43:31 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_refresh_token
     *
     * @mbg.generated Mon Oct 12 11:43:31 CST 2020
     */
    int insert(RefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_refresh_token
     *
     * @mbg.generated Mon Oct 12 11:43:31 CST 2020
     */
    RefreshToken selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_refresh_token
     *
     * @mbg.generated Mon Oct 12 11:43:31 CST 2020
     */
    List<RefreshToken> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_refresh_token
     *
     * @mbg.generated Mon Oct 12 11:43:31 CST 2020
     */
    int updateByPrimaryKey(RefreshToken record);

    /**
     * 通过tokenKey查RefreshToken
     * @param pcTokenKey
     * @return
     */
    RefreshToken selectByPCTokenKey(String pcTokenKey);

    /**
     * 通过user_id删除RefreshToken
     * @param userId
     * @return
     */
    int deleteByUserId(String userId);

    /**
     * 通过tokenKey删除RefreshToken
     * @param tokenKey
     * @return
     */
    int deleteByTokenKey(String tokenKey);

    int updateMobileTokenKey(String MobileTokenKey);

    int updatePCTokenKey(String PCTokenKey);

    RefreshToken selectByUserId(String userId);

    RefreshToken selectByMobileTokenKey(String mobileTokenKey);
}