package com.polaris.blog.dao;

import com.polaris.blog.pojo.Setting;
import java.util.List;
import java.util.Set;

public interface SettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_setting
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_setting
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_setting
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    Setting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_setting
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    List<Setting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_setting
     *
     * @mbg.generated Sun Oct 04 17:25:41 CST 2020
     */
    int updateByPrimaryKey(Setting record);


    /**
     * 通过key查Setting
     * @param key
     * @return
     */
    Setting selectByKey(String key);
}